config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-accounting:
      branch: devel
      repo: https://github.com/ARGOeu/argo-accounting
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-brown-orangutan.sh
        container: qc.acc_wimpy-firebrick-robin
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-accounting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-xanthic-mayfly.sh
        container: qc.doc_hasty-sapphire-urchin
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-myrtle-chihuahua.sh
        container: qc.doc_bluesy-yellow-binturong
      github.com/ARGOeu/argo-accounting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-orchid-walrus.sh
        container: qc.doc_nerdy-chartreuse-civet
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-accounting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-crimson-labradoodle.sh
        container: qc.lic_chummy-plum-rattlesnake
  QC.Met:
    repos:
      github.com/ARGOeu/argo-accounting cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-orange-wombat.sh
        container: qc.met_tasty-burgundy-cassowary
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-accounting checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-amaranth-dalmatian.sh
        container: qc.sty_wimpy-cardinal-mandrill
      github.com/ARGOeu/argo-accounting hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-smalt-dunker.sh
        container: qc.sty_nippy-ivory-fly
      github.com/ARGOeu/argo-accounting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-aqua-cougar.sh
        container: qc.sty_lumpy-rose-balinese
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-accounting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-lavender-butterfly.sh
        container: qc.ver_scaly-lilac-snake
timeout: 5400
