config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-accounting:
      branch: devel
      repo: https://github.com/ARGOeu/argo-accounting
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-aquamarine-dog.sh
        container: qc.acc_ready-puce-spider
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-accounting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-gold-turkey.sh
        container: qc.doc_randy-maroon-sponge
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-lavender-oyster.sh
        container: qc.doc_woozy-lavender-lynx
      github.com/ARGOeu/argo-accounting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-firebrick-vole.sh
        container: qc.doc_bluesy-white-jaguar
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-accounting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-sapphire-toad.sh
        container: qc.lic_tasty-taupe-capuchin
  QC.Met:
    repos:
      github.com/ARGOeu/argo-accounting cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-auburn-catfish.sh
        container: qc.met_skanky-salmon-panda
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-accounting checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-cream-mongoose.sh
        container: qc.sty_cheeky-cobalt-squid
      github.com/ARGOeu/argo-accounting hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-grey-antelope.sh
        container: qc.sty_crappy-ultramarine-rat
      github.com/ARGOeu/argo-accounting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-amaranth-bandicoot.sh
        container: qc.sty_dorky-rust-ant
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-accounting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-chestnut-abyssinian.sh
        container: qc.ver_clammy-ochre-caterpillar
timeout: 5400
