config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-accounting:
      branch: devel
      repo: https://github.com/ARGOeu/argo-accounting
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.beady-green-ray.sh
        container: qc.acc_pretty-teal-alligator
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-accounting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-ivory-horse.sh
        container: qc.doc_goopy-cream-serval
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-pink-gorilla.sh
        container: qc.doc_freaky-gamboge-newt
      github.com/ARGOeu/argo-accounting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.homely-charcoal-greyhound.sh
        container: qc.doc_skimpy-viridian-penguin
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-accounting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-purple-hyrax.sh
        container: qc.lic_skimpy-ochre-jellyfish
  QC.Met:
    repos:
      github.com/ARGOeu/argo-accounting cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-tan-dhole.sh
        container: qc.met_smelly-corn-civet
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-accounting checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-crimson-axolotl.sh
        container: qc.sty_tasty-grey-cichlid
      github.com/ARGOeu/argo-accounting hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-alizarin-skunk.sh
        container: qc.sty_squeaky-crimson-akbash
      github.com/ARGOeu/argo-accounting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-gold-mole.sh
        container: qc.sty_crappy-brown-antelope
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-accounting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-coral-opossum.sh
        container: qc.ver_jumpy-cinnamon-impala
timeout: 5400
