config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-accounting:
      branch: devel
      repo: https://github.com/ARGOeu/argo-accounting
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-apricot-dugong.sh
        container: qc.acc_slimy-yellow-iguana
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-accounting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-taupe-chinchilla.sh
        container: qc.doc_squirrely-emerald-cow
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-charcoal-slug.sh
        container: qc.doc_baggy-white-kangaroo
      github.com/ARGOeu/argo-accounting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-turquoise-shrew.sh
        container: qc.doc_paltry-coral-mouse
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-accounting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.silly-coral-camel.sh
        container: qc.lic_hazy-red-opossum
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-accounting checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-scarlet-barb.sh
        container: qc.sty_wiggy-brown-tuatara
      github.com/ARGOeu/argo-accounting hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-gamboge-rhinoceros.sh
        container: qc.sty_goopy-harlequin-toad
      github.com/ARGOeu/argo-accounting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-goldenrod-squid.sh
        container: qc.sty_tacky-turquoise-coyote
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-accounting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-blue-jaguar.sh
        container: qc.ver_gimpy-lilac-wolverine
timeout: 5400
