config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-accounting:
      branch: devel
      repo: https://github.com/ARGOeu/argo-accounting
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-crimson-fousek.sh
        container: qc.acc_nippy-scarlet-tiger
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-accounting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-crimson-gar.sh
        container: qc.doc_cranky-magenta-capybara
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-azure-dunker.sh
        container: qc.doc_homey-gamboge-dodo
      github.com/ARGOeu/argo-accounting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-white-stingray.sh
        container: qc.doc_gamy-alizarin-chameleon
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-accounting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-russet-seahorse.sh
        container: qc.lic_lovely-flax-mandrill
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-accounting checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-olivine-starfish.sh
        container: qc.sty_beady-cornflower-dalmatian
      github.com/ARGOeu/argo-accounting hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-salmon-gibbon.sh
        container: qc.sty_boozy-orchid-coati
      github.com/ARGOeu/argo-accounting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-mustard-sheepdog.sh
        container: qc.sty_muggy-crimson-woodlouse
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-accounting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-brass-baboon.sh
        container: qc.ver_woozy-cornflower-fousek
timeout: 5400
