config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/argoeu/argo-accounting:
      branch: devel
      repo: https://github.com/argoeu/argo-accounting
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/argoeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-azure-wasp.sh
        container: qc.acc_snoopy-burgundy-jackal
  QC.Doc:
    repos:
      github.com/argoeu/argo-accounting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-magenta-dugong.sh
        container: qc.doc_shaky-jade-loon
      github.com/argoeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-cerulean-dachshund.sh
        container: qc.doc_clammy-apricot-cuttlefish
      github.com/argoeu/argo-accounting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-tan-monster.sh
        container: qc.doc_snappy-pink-fly
  QC.Lic:
    repos:
      github.com/argoeu/argo-accounting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-wisteria-wildebeest.sh
        container: qc.lic_crabby-champagne-moth
  QC.Sty:
    repos:
      github.com/argoeu/argo-accounting checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-cobalt-monster.sh
        container: qc.sty_droopy-aquamarine-gecko
      github.com/argoeu/argo-accounting hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-myrtle-jellyfish.sh
        container: qc.sty_silly-yellow-angora
      github.com/argoeu/argo-accounting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-magenta-seal.sh
        container: qc.sty_baggy-brown-squirt
  QC.Ver:
    repos:
      github.com/argoeu/argo-accounting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-sangria-gar.sh
        container: qc.ver_crappy-vermilion-ladybird
timeout: 5400
