config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/argoeu/argo-accounting:
      branch: devel
      repo: https://github.com/argoeu/argo-accounting
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/argoeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-wheat-liger.sh
        container: qc.acc_silly-chestnut-grasshopper
  QC.Doc:
    repos:
      github.com/argoeu/argo-accounting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-olive-tang.sh
        container: qc.doc_crappy-tan-nightingale
      github.com/argoeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-tan-leopard.sh
        container: qc.doc_stealthy-chartreuse-macaque
      github.com/argoeu/argo-accounting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-chestnut-crane.sh
        container: qc.doc_shaky-salmon-uakari
  QC.Lic:
    repos:
      github.com/argoeu/argo-accounting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-mauve-mastiff.sh
        container: qc.lic_breezy-amber-coati
  QC.Sty:
    repos:
      github.com/argoeu/argo-accounting checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-wheat-badger.sh
        container: qc.sty_snappy-jade-dachshund
      github.com/argoeu/argo-accounting hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-celadon-yak.sh
        container: qc.sty_smelly-ivory-terrier
      github.com/argoeu/argo-accounting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-linen-devil.sh
        container: qc.sty_flabby-fuchsia-falcon
  QC.Ver:
    repos:
      github.com/argoeu/argo-accounting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-cobalt-serval.sh
        container: qc.ver_crabby-heliotrope-fowl
timeout: 5400
