config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/argoeu/argo-accounting:
      branch: devel
      repo: https://github.com/argoeu/argo-accounting
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/argoeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-cream-cassowary.sh
        container: qc.acc_sunny-brown-discus
  QC.Doc:
    repos:
      github.com/argoeu/argo-accounting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-thistle-akbash.sh
        container: qc.doc_shaky-red-gerbil
      github.com/argoeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-amber-rhinoceros.sh
        container: qc.doc_craggy-aquamarine-birman
      github.com/argoeu/argo-accounting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-turquoise-akbash.sh
        container: qc.doc_beady-scarlet-gerbil
  QC.Lic:
    repos:
      github.com/argoeu/argo-accounting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-amethyst-balinese.sh
        container: qc.lic_skinny-crimson-fossa
  QC.Sty:
    repos:
      github.com/argoeu/argo-accounting checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-red-olm.sh
        container: qc.sty_leaky-ruby-devil
      github.com/argoeu/argo-accounting hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-buff-bird.sh
        container: qc.sty_zippy-alizarin-dalmatian
      github.com/argoeu/argo-accounting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-khaki-badger.sh
        container: qc.sty_cheeky-sapphire-tetra
  QC.Ver:
    repos:
      github.com/argoeu/argo-accounting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-rust-argentino.sh
        container: qc.ver_stuffy-brass-penguin
timeout: 5400
