config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-accounting:
      branch: devel
      repo: https://github.com/ARGOeu/argo-accounting
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.ready-tangerine-hare.sh
        container: qc.acc_ugly-white-dugong
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-accounting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-rust-terrier.sh
        container: qc.doc_chummy-periwinkle-maltese
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-olivine-mau.sh
        container: qc.doc_skanky-ochre-liger
      github.com/ARGOeu/argo-accounting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-ochre-akita.sh
        container: qc.doc_scummy-blue-dingo
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-accounting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-denim-dachsbracke.sh
        container: qc.lic_snippy-auburn-paradise
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-accounting checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-buff-olm.sh
        container: qc.sty_dorky-charcoal-eleuth
      github.com/ARGOeu/argo-accounting hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-auburn-hamster.sh
        container: qc.sty_crappy-brass-angelfish
      github.com/ARGOeu/argo-accounting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-plum-hare.sh
        container: qc.sty_woolly-asparagus-termite
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-accounting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-wisteria-tiger.sh
        container: qc.ver_shaky-black-barb
timeout: 5400
