config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/argoeu/argo-accounting:
      branch: devel
      repo: https://github.com/argoeu/argo-accounting
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/argoeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-green-chamois.sh
        container: qc.acc_lumpy-brass-squid
  QC.Doc:
    repos:
      github.com/argoeu/argo-accounting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.surly-heliotrope-drever.sh
        container: qc.doc_sickly-ivory-dachsbracke
      github.com/argoeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-wheat-caterpillar.sh
        container: qc.doc_woolly-tomato-quokka
      github.com/argoeu/argo-accounting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-orchid-tetra.sh
        container: qc.doc_frumpy-copper-lemur
  QC.Lic:
    repos:
      github.com/argoeu/argo-accounting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-apricot-robin.sh
        container: qc.lic_shaggy-teal-woodlouse
  QC.Sty:
    repos:
      github.com/argoeu/argo-accounting checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-lime-cuscus.sh
        container: qc.sty_scaly-amaranth-cow
      github.com/argoeu/argo-accounting hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-viridian-falcon.sh
        container: qc.sty_nippy-buff-hamster
      github.com/argoeu/argo-accounting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-chartreuse-crab.sh
        container: qc.sty_muggy-dandelion-dingo
  QC.Ver:
    repos:
      github.com/argoeu/argo-accounting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-firebrick-shark.sh
        container: qc.ver_sickly-chocolate-hyrax
timeout: 5400
