config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/argoeu/argo-accounting:
      branch: devel
      repo: https://github.com/argoeu/argo-accounting
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/argoeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-chartreuse-orangutan.sh
        container: qc.acc_pasty-sapphire-oyster
  QC.Doc:
    repos:
      github.com/argoeu/argo-accounting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-orchid-retriever.sh
        container: qc.doc_jumpy-lavender-millipede
      github.com/argoeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-aqua-beagle.sh
        container: qc.doc_scanty-malachite-wolverine
      github.com/argoeu/argo-accounting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-lemon-rat.sh
        container: qc.doc_cranky-cerise-frise
  QC.Lic:
    repos:
      github.com/argoeu/argo-accounting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-chartreuse-chow.sh
        container: qc.lic_frumpy-persimmon-bat
  QC.Sty:
    repos:
      github.com/argoeu/argo-accounting checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-bronze-rabbit.sh
        container: qc.sty_muzzy-lime-shrimp
      github.com/argoeu/argo-accounting hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-tomato-caiman.sh
        container: qc.sty_zippy-magenta-armadillo
      github.com/argoeu/argo-accounting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-malachite-eleuth.sh
        container: qc.sty_jumpy-aqua-gorilla
  QC.Ver:
    repos:
      github.com/argoeu/argo-accounting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-chartreuse-tang.sh
        container: qc.ver_shaggy-bistre-monster
timeout: 5400
