config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/argoeu/argo-accounting:
      branch: devel
      repo: https://github.com/argoeu/argo-accounting
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/argoeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-black-kangaroo.sh
        container: qc.acc_queasy-orchid-bloodhound
  QC.Doc:
    repos:
      github.com/argoeu/argo-accounting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-amaranth-termite.sh
        container: qc.doc_freaky-ecru-baboon
      github.com/argoeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-flax-sparrow.sh
        container: qc.doc_nerdy-green-serval
      github.com/argoeu/argo-accounting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-black-lemming.sh
        container: qc.doc_messy-xanthic-salamander
  QC.Lic:
    repos:
      github.com/argoeu/argo-accounting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-goldenrod-mole.sh
        container: qc.lic_woozy-ultramarine-binturong
  QC.Sty:
    repos:
      github.com/argoeu/argo-accounting checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-pear-sparrow.sh
        container: qc.sty_shaky-aqua-frise
      github.com/argoeu/argo-accounting hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-purple-ragdoll.sh
        container: qc.sty_pasty-apricot-dolphin
      github.com/argoeu/argo-accounting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-magnolia-dalmatian.sh
        container: qc.sty_pasty-green-tapir
  QC.Ver:
    repos:
      github.com/argoeu/argo-accounting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-copper-chameleon.sh
        container: qc.ver_tasty-sapphire-bongo
timeout: 5400
