config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/argoeu/argo-accounting:
      branch: devel
      repo: https://github.com/argoeu/argo-accounting
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/argoeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-puce-snail.sh
        container: qc.acc_snoopy-indigo-ferret
  QC.Doc:
    repos:
      github.com/argoeu/argo-accounting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-cardinal-tzu.sh
        container: qc.doc_snazzy-auburn-hyena
      github.com/argoeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-yellow-leopard.sh
        container: qc.doc_silly-viridian-lionfish
      github.com/argoeu/argo-accounting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-amber-uakari.sh
        container: qc.doc_flaky-lavender-mist
  QC.Lic:
    repos:
      github.com/argoeu/argo-accounting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-pear-bordeaux.sh
        container: qc.lic_crappy-seashell-duck
  QC.Sty:
    repos:
      github.com/argoeu/argo-accounting checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-burgundy-grouse.sh
        container: qc.sty_smelly-aquamarine-opossum
      github.com/argoeu/argo-accounting hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-buff-harrier.sh
        container: qc.sty_stealthy-eggplant-falcon
      github.com/argoeu/argo-accounting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-black-salamander.sh
        container: qc.sty_skanky-heliotrope-malamute
  QC.Ver:
    repos:
      github.com/argoeu/argo-accounting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-pumpkin-fossa.sh
        container: qc.ver_woolly-bistre-squirrel
timeout: 5400
