config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/argoeu/argo-accounting:
      branch: devel
      repo: https://github.com/argoeu/argo-accounting
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/argoeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-lemon-buzzard.sh
        container: qc.acc_ready-magenta-bandicoot
  QC.Doc:
    repos:
      github.com/argoeu/argo-accounting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-sepia-chipmunk.sh
        container: qc.doc_gamy-auburn-gopher
      github.com/argoeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-silver-shark.sh
        container: qc.doc_greasy-coral-tapir
      github.com/argoeu/argo-accounting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-wheat-spoonbill.sh
        container: qc.doc_skinny-chocolate-wolverine
  QC.Lic:
    repos:
      github.com/argoeu/argo-accounting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.silly-sepia-harrier.sh
        container: qc.lic_lovely-yellow-binturong
  QC.Sty:
    repos:
      github.com/argoeu/argo-accounting checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-zucchini-mouse.sh
        container: qc.sty_grumpy-celadon-butterfly
      github.com/argoeu/argo-accounting hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-aqua-moth.sh
        container: qc.sty_frumpy-heliotrope-bandicoot
      github.com/argoeu/argo-accounting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-turquoise-wasp.sh
        container: qc.sty_chummy-black-spaniel
  QC.Ver:
    repos:
      github.com/argoeu/argo-accounting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-mauve-butterfly.sh
        container: qc.ver_woozy-amaranth-chihuahua
timeout: 5400
