config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-accounting:
      branch: devel
      repo: https://github.com/ARGOeu/argo-accounting
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-firebrick-hyrax.sh
        container: qc.acc_wimpy-cinnabar-crane
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-accounting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-emerald-gar.sh
        container: qc.doc_silly-beige-centipede
      github.com/ARGOeu/argo-accounting git:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-chestnut-opossum.sh
        container: qc.doc_gamy-plum-snake
      github.com/ARGOeu/argo-accounting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-cream-gorilla.sh
        container: qc.doc_dorky-purple-impala
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-accounting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.randy-sapphire-saola.sh
        container: qc.lic_wiggy-yellow-bordeaux
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-accounting checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.randy-maroon-coyote.sh
        container: qc.sty_ready-celadon-forest
      github.com/ARGOeu/argo-accounting hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-firebrick-dingo.sh
        container: qc.sty_slaphappy-alizarin-mastiff
      github.com/ARGOeu/argo-accounting jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-lime-urchin.sh
        container: qc.sty_snappy-cornflower-wallaby
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-accounting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-magnolia-cassowary.sh
        container: qc.ver_ugly-mauve-tamarin
timeout: 5400
